version: "3"
services:
  monapp:
    image: imagetestdockerfile2
    depends_on :
      - redis
    ports:
      - "80:80"
    networks:
      - monreseau
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - monreseau
networks:
  monreseau: